---
title: "Note about parenting"
date: 2023-11-20T14:27:04+01:00
draft: false
tags:
- parenting
- self-improvement
---

I started collecting books on parenting and bookmarking blogs about parenting soon after my wife became pregnant with our first child. However, with no first-hand experience of raising a child, the books didn't make much sense to me. My realization that parenting is subjective and should depend upon the nature of the child I completely gave up the idea of learning from books. I wanted to write about some of my opinions (personal and inspired[1]) of parenting while I am still learning the ropes.

* Being the person you want your child to be

A young child imitates their parents. Leveraging this fact, small behavioral changes and habit reinforcement can easily be introduced by you doing the action. This might be obvious for many, but seeing the results felt like magic. My first success was when I had to make my daughter drink a very bitter tonic meant to cure her constipation issues. The first few days, we almost had to force her to drink. I felt there should be a better way to do it. One day I didn't bring her the tonic but instead poured a little in a glass and drank it myself, and did the same the next day. Now my daughter wanted to have the same fun I was having, and from then on she took her medicine effortlessly and voluntarily. I try to be the person I want my daughter to be, and it has worked well for me.

* Conscious parent

You being a parent doesn't naturally make you the owner of the child. We should only water the plant, and be the nourishing soil and source of supply of nutrients until the plant is on its own. The tree could be a neem tree an orange tree or whatever tree they are meant to be. If you had to ever punish the child, do it consciously. If you are angry and punishing, you might be taking your revenge. Be a conscious parent.

* Environment

The best thing you can provide the child is an environment free from anger and frustration. This requires we work on ourselves first, the rest will fall in place. 


* Time

A child needs your time. Quality time with the child doesn't require any toys, although little attention and energy is needed. Most importantly keep the phone away.

To have the mental space and energy to have the patience, to be involved in all aspects of being a parent requires work upon self. Personaly, meditation, yoga and living away from a big city help me.

[1] Most of the ideas are direct inspiration of Sadhguru's teachings.
