---
title: "Productivity First Steps"
date: 2018-04-15T14:15:30+02:00
draft: false
tags:
- self-improvement
- productivity
---

I wanted to share with my friends some of productivity practices I am trying to imbibe in my routine which are giving results. Writing this help me put my ideas in order and I can share without repeating. And here it is. For me being productive is to have more time. The judgement of what is required and what is not, what is worth perusing and what isn't is a skill to develop. My inspiration  for productivity arises from a thought that having time to waste is the greatest of all luxuries. When I realized this luxury came at a bigger cost and seemed not affordable. If you appreciate that having  time for yourself and for things you care about, please read further.

*Cutting down the crap*

How often we become restless when the phone the battery falls below 10% ? Probably everyday. Social media is successful in making oneself feel their own life is miserable.

I removed myself from social media which didn't add much value to me. I still have twitter account, I try to carefully use it by un-following those spamming; Spam: those information doesn't add value to life.
I try to not read news, and not spend my cognitive energy on sensational data from the internet. I would rather not have a conversation if that was the only purpose of reading news. "Low information diet" as called in Four hour work week.

*Goals*

How do I effectively make judgements about what is important and what is worth perusing. This is a constant effort and enough time spent on planning each day is crucial, because this keeps me in line with my goals.

** Plan bottom up
   - Write down the plans for the year
   - Write down the plans for 6 months
   - Write down plans for 3 months
   - Write down plans for 1 month
   - Write down plans for this week
   - Write down plan for today

Tip: Make plans for the next day the previous evening.

** execute top down
   - Plan the day, such that it makes sense to achieve goals for the week, and plan goals for the week that is in line with monthly goal. and monthly goal inline with quarterly goal and in turn year's goal.
   - Goals and plans change, review and audit if goals meet your plans.
   - Keep everyday goals small and achievable, this is required for improved flow of confidence and increased serotonin release.
   - Spend time to prepare/study to execute goals, unprepared mind will lead to stress. (todo: write an post :P)

All the goals require auditing, spend time to review your progress.

Benefits: Chaos to Order, effective use of time and self improvement.

** Life style + attitude


Work for yourself. There is no one with altruistic intentions. Create your work that will benefit others.
Design your day, find early successes. Find out things that make you feel successful, can it be making your breakfast? Or making your bed?
Habits should work like a well oiled machinery. effortlessly automatic. Create habits that benefit you. Compounding effect of even something small over a period would bring great results.
Exercise: healthy body/mind is crucial to execute those goals, Goals doesn't make sense if you sick and tired. I follow the seven minute workout. I recommend it. 7 minutes for 7 days a week, think of benefits if done for a year.
Meditate.
Don't skip breakfast.


* Take feedback

Constant improvement is a value. Ask for feedback from person you trust, and gracefully think through them and if it makes sense,  work on it.

Conclusion

While I strive to follow my own advice, these ideas have put much of my life in order.


Special thanks to Murat for helping me fix my lousy English and trim the post.

