---
title: "Hiragana First Steps"
date: 2018-05-22T23:43:08+02:00
tags:
- japanese
- languages
categories:
- learning language
draft: false
---


* Learning Japanese 1
  Welcome to learning Japanese, this is how I am planning to learn Japanese without a teacher. I am writing this series for myself to keep track of my progress, more of notes.
  
  I already have some materials given by my teacher and know some fundamentals. Here are some links I find very useful.

  - https://www.tofugu.com/japanese/learn-hiragana/
  - https://www.nhk.or.jp/lesson/english/syllabary/index.html
  I am going to follow my teacher’s methods: learn the Hiragana characters, learn some words and create basic sentences

  Laying the strong foundations: mastering the vowels
  | あ | aa | (pronounce a as in all)      |
  | い | e  | (pronounce e as in enough)   |
  | う | Uh |                              |
  | え | é  | (pronounce e as in hey)      |
  | お | ô  | (pronounce o as in Hospital) |


  _Words with above characters_

  | あい   | Love   |
  | あお   | Blue   |
  | いえ   | House  |
  | いいえ | No     |
  | うえ   | Top    |
  | おい   | Nephew |
  | あう   | Meet   |


** Spoken helpers:
  - /Yes/ is pronounced as ‘Hai’
  - /No/ is pronounced as いいえ (e-e-a)
   

** Update:
More youtube video links
-  
